apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: homeshield
spec:
  selector:
    app: homeshield-backend
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: ClusterIP
