apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: homeshield
spec:
  selector:
    app: homeshield-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
  # For local Minikube, change type to NodePort:
  # type: NodePort
